version: '3.8'

services:
  # 1. AZ ADATBÁZIS
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: kulturvadasz
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. A BACKEND (Node.js)
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=kulturvadasz
    depends_on:
      - mysql-db

  # 3. A FRONTEND (React)
  frontend:
    build: ./frontend

    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  mysql_data: